apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
spec:
  containers:
  - name: agent
    image: natog/jenkins-agent:latest
    imagePullPolicy: Always
    command:
      - /bin/sh
      - -c
      - "nohup sh -c 'dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay2' > /var/log/docker.log 2>&1 &"

      # - "dockerd --privileged=true -D --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay2 & wait $!"
      # - |
      #   dockerd
    # command:
    #   - sleep
    # args:
    #   - "sleep"
    #   - "9999"
    env:
      - name: JENKINS_SECRET
        value: "${computer.jnlpmac}"
      - name: JENKINS_NAME
        value: "${computer.name}"
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
       - name: dockersock
         mountPath: /var/run/docker.sock
  volumes:
   - name: dockersock
     hostPath: 
       path: /var/run/docker.sock