apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  # namespace: jenkins
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/jenkins

# Working PV 31.3.23
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins-pv
#   # namespace: jenkins
#   annotations:
#     pv.beta.kubernetes.io/gid: "1000"
# spec:
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 5Gi
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: /Users/nato/dev/DevOpsInterviewAssignment/jenkins
