apiVersion: v1
kind: Pod
metadata:
  name: nato-docker-test
spec:
  containers:
  - name: docker
    image: docker:20.10.10
    command:
    - cat
    tty: true
    # volumeMounts:
    #   - name: docker-graph-storage
    #     mountPath: /var/lib/docker
  # volumes:
  # - name: docker-graph-storage
  #   emptyDir: {}
